#!/bin/sh
# Can be used in two ways, './lint' or './lint --check'
if ! which black isort mypy >/dev/null; then
    echo "can't find stuff, is venv active?"
    exit 1
fi
black pacman/ "$@" || error=yes
isort pacman/ "$@" || error=yes
mypy --strict pacman/ || error=yes
[ "$error" != yes ] || exit 1
